<?php
/** @var \Economix\Usersnap\Block\FrontendWidget $block */
?>

<script>
    window.onUsersnapCXLoad = function(api) {
        api.init();
        window.Usersnap = api;
    }
    var script = document.createElement('script');
    script.async = 1;
    script.src = 'https://widget.usersnap.com/load/<?= $block->getProjectApiKey(); ?>?onload=onUsersnapCXLoad';
    document.getElementsByTagName('head')[0].appendChild(script);
</script>
